apiVersion: v1
kind: Service
metadata:
  namespace: uptime-kuma
  name: uptime-kuma
spec:
  type: NodePort
  selector:
    app: uptime-kuma
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 30301
